## AUTH

### LOGIN
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "username": "johndoe",
  "password": "password123"
}

### REFRESH
POST http://localhost:8080/api/v1/auth/refresh
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

### LOGOUT
POST http://localhost:8080/api/v1/auth/logout
Content-Type: application/json

{
  "jwt": "{{jwt}}",
  "refreshToken": "{{refreshToken}}"
}